require: rubocop-rails
require: rubocop-performance
require: rubocop-rspec

# Treat offenses as warnings instead of errors
AllCops:
  Severity: warning
# Treat Layout/LineLength offenses as warnings
Layout/LineLength:
  Severity: warning
